[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "18"

[build.processing.html]
  pretty_urls = true

[[plugins]]
  package = "@netlify/plugin-nextjs" 